receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  metric_processor:
    redis_addr: localhost:6379

exporters:
  debug:
    verbosity: detailed
  kafka:
    brokers:
      - localhost:9092
    topic: bifrost
    encoding: json
    # compression: gzip
    # batch_size: 1024

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [metric_processor]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] 